/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace LoanManager {
  export type LoanStruct = {
    id: BigNumberish;
    borrower: AddressLike;
    lender: AddressLike;
    amountINR: BigNumberish;
    collateralToken: AddressLike;
    collateralAmount: BigNumberish;
    status: BigNumberish;
    createdAt: BigNumberish;
    activatedAt: BigNumberish;
    settledAt: BigNumberish;
    offchainId: string;
  };

  export type LoanStructOutput = [
    id: bigint,
    borrower: string,
    lender: string,
    amountINR: bigint,
    collateralToken: string,
    collateralAmount: bigint,
    status: bigint,
    createdAt: bigint,
    activatedAt: bigint,
    settledAt: bigint,
    offchainId: string
  ] & {
    id: bigint;
    borrower: string;
    lender: string;
    amountINR: bigint;
    collateralToken: string;
    collateralAmount: bigint;
    status: bigint;
    createdAt: bigint;
    activatedAt: bigint;
    settledAt: bigint;
    offchainId: string;
  };
}

export interface LoanManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activateLoan"
      | "cancelLoan"
      | "createLoan"
      | "defaultLoan"
      | "getBorrowerLoans"
      | "getLenderLoans"
      | "getLoan"
      | "repayLoan"
      | "totalLoans"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LoanActivated"
      | "LoanCancelled"
      | "LoanCreated"
      | "LoanDefaulted"
      | "LoanRepaid"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activateLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createLoan",
    values: [AddressLike, BigNumberish, AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBorrowerLoans",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLenderLoans",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "repayLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalLoans",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "activateLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelLoan", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "defaultLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBorrowerLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLenderLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLoan", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "repayLoan", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalLoans", data: BytesLike): Result;
}

export namespace LoanActivatedEvent {
  export type InputTuple = [loanId: BigNumberish, lender: AddressLike];
  export type OutputTuple = [loanId: bigint, lender: string];
  export interface OutputObject {
    loanId: bigint;
    lender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanCancelledEvent {
  export type InputTuple = [loanId: BigNumberish, borrower: AddressLike];
  export type OutputTuple = [loanId: bigint, borrower: string];
  export interface OutputObject {
    loanId: bigint;
    borrower: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanCreatedEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    borrower: AddressLike,
    lender: AddressLike,
    amountINR: BigNumberish,
    collateralToken: AddressLike,
    collateralAmount: BigNumberish,
    offchainId: string
  ];
  export type OutputTuple = [
    loanId: bigint,
    borrower: string,
    lender: string,
    amountINR: bigint,
    collateralToken: string,
    collateralAmount: bigint,
    offchainId: string
  ];
  export interface OutputObject {
    loanId: bigint;
    borrower: string;
    lender: string;
    amountINR: bigint;
    collateralToken: string;
    collateralAmount: bigint;
    offchainId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanDefaultedEvent {
  export type InputTuple = [loanId: BigNumberish, lender: AddressLike];
  export type OutputTuple = [loanId: bigint, lender: string];
  export interface OutputObject {
    loanId: bigint;
    lender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanRepaidEvent {
  export type InputTuple = [loanId: BigNumberish, borrower: AddressLike];
  export type OutputTuple = [loanId: bigint, borrower: string];
  export interface OutputObject {
    loanId: bigint;
    borrower: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LoanManager extends BaseContract {
  connect(runner?: ContractRunner | null): LoanManager;
  waitForDeployment(): Promise<this>;

  interface: LoanManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activateLoan: TypedContractMethod<
    [loanId: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelLoan: TypedContractMethod<[loanId: BigNumberish], [void], "nonpayable">;

  createLoan: TypedContractMethod<
    [
      lender: AddressLike,
      amountINR: BigNumberish,
      collateralToken: AddressLike,
      collateralAmount: BigNumberish,
      offchainId: string
    ],
    [bigint],
    "nonpayable"
  >;

  defaultLoan: TypedContractMethod<
    [loanId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getBorrowerLoans: TypedContractMethod<
    [borrower: AddressLike],
    [bigint[]],
    "view"
  >;

  getLenderLoans: TypedContractMethod<
    [lender: AddressLike],
    [bigint[]],
    "view"
  >;

  getLoan: TypedContractMethod<
    [loanId: BigNumberish],
    [LoanManager.LoanStructOutput],
    "view"
  >;

  repayLoan: TypedContractMethod<[loanId: BigNumberish], [void], "nonpayable">;

  totalLoans: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activateLoan"
  ): TypedContractMethod<[loanId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelLoan"
  ): TypedContractMethod<[loanId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createLoan"
  ): TypedContractMethod<
    [
      lender: AddressLike,
      amountINR: BigNumberish,
      collateralToken: AddressLike,
      collateralAmount: BigNumberish,
      offchainId: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "defaultLoan"
  ): TypedContractMethod<[loanId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getBorrowerLoans"
  ): TypedContractMethod<[borrower: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getLenderLoans"
  ): TypedContractMethod<[lender: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getLoan"
  ): TypedContractMethod<
    [loanId: BigNumberish],
    [LoanManager.LoanStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "repayLoan"
  ): TypedContractMethod<[loanId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalLoans"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "LoanActivated"
  ): TypedContractEvent<
    LoanActivatedEvent.InputTuple,
    LoanActivatedEvent.OutputTuple,
    LoanActivatedEvent.OutputObject
  >;
  getEvent(
    key: "LoanCancelled"
  ): TypedContractEvent<
    LoanCancelledEvent.InputTuple,
    LoanCancelledEvent.OutputTuple,
    LoanCancelledEvent.OutputObject
  >;
  getEvent(
    key: "LoanCreated"
  ): TypedContractEvent<
    LoanCreatedEvent.InputTuple,
    LoanCreatedEvent.OutputTuple,
    LoanCreatedEvent.OutputObject
  >;
  getEvent(
    key: "LoanDefaulted"
  ): TypedContractEvent<
    LoanDefaultedEvent.InputTuple,
    LoanDefaultedEvent.OutputTuple,
    LoanDefaultedEvent.OutputObject
  >;
  getEvent(
    key: "LoanRepaid"
  ): TypedContractEvent<
    LoanRepaidEvent.InputTuple,
    LoanRepaidEvent.OutputTuple,
    LoanRepaidEvent.OutputObject
  >;

  filters: {
    "LoanActivated(uint256,address)": TypedContractEvent<
      LoanActivatedEvent.InputTuple,
      LoanActivatedEvent.OutputTuple,
      LoanActivatedEvent.OutputObject
    >;
    LoanActivated: TypedContractEvent<
      LoanActivatedEvent.InputTuple,
      LoanActivatedEvent.OutputTuple,
      LoanActivatedEvent.OutputObject
    >;

    "LoanCancelled(uint256,address)": TypedContractEvent<
      LoanCancelledEvent.InputTuple,
      LoanCancelledEvent.OutputTuple,
      LoanCancelledEvent.OutputObject
    >;
    LoanCancelled: TypedContractEvent<
      LoanCancelledEvent.InputTuple,
      LoanCancelledEvent.OutputTuple,
      LoanCancelledEvent.OutputObject
    >;

    "LoanCreated(uint256,address,address,uint256,address,uint256,string)": TypedContractEvent<
      LoanCreatedEvent.InputTuple,
      LoanCreatedEvent.OutputTuple,
      LoanCreatedEvent.OutputObject
    >;
    LoanCreated: TypedContractEvent<
      LoanCreatedEvent.InputTuple,
      LoanCreatedEvent.OutputTuple,
      LoanCreatedEvent.OutputObject
    >;

    "LoanDefaulted(uint256,address)": TypedContractEvent<
      LoanDefaultedEvent.InputTuple,
      LoanDefaultedEvent.OutputTuple,
      LoanDefaultedEvent.OutputObject
    >;
    LoanDefaulted: TypedContractEvent<
      LoanDefaultedEvent.InputTuple,
      LoanDefaultedEvent.OutputTuple,
      LoanDefaultedEvent.OutputObject
    >;

    "LoanRepaid(uint256,address)": TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;
    LoanRepaid: TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;
  };
}
